CREATE DATABASE IF NOT EXISTS event_planner;
USE event_planner;

CREATE TABLE IF NOT EXISTS Users (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Events (
    Event_ID INT AUTO_INCREMENT PRIMARY KEY,
    Organizer_ID INT NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Theme VARCHAR(150) NOT NULL,
    Date DATE NOT NULL,
    Venue VARCHAR(200) NOT NULL,
    FOREIGN KEY (Organizer_ID) REFERENCES Users(User_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Bookings (
    Booking_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Event_ID INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (Event_ID) REFERENCES Events(Event_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    UNIQUE KEY unique_booking (User_ID, Event_ID)
);
